apply plugin: "java"
apply plugin: "idea"
apply plugin: "application"

sourceCompatibility = JavaVersion.VERSION_11
targetCompatibility = JavaVersion.VERSION_11

version = "1.7.3-Beta"

subprojects {
    apply plugin: "java"
    apply plugin: "idea"

    repositories {
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
    
    dependencies {
        compile group: 'it.unimi.dsi', name: 'fastutil', version: '8.2.2'
    }
}

task wrapper(type: Wrapper) {
    gradleVersion = '4.10.2'
}

