plugins {
    id 'java'
    id 'idea'
    id 'application'
}


allprojects {
    apply plugin: 'idea'
    apply plugin: 'java'

    group = "net.potion"
    version = "1.7.3-Beta"

    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17

    repositories {
        mavenLocal()
        mavenCentral()
        maven { url "https://jitpack.io/" }
        maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
    }
}
