apply plugin: 'java'
apply plugin: 'application'

application.mainClassName = "net.potion.client.Starter"

project.ext.lwjglVersion = "3.2.2"
project.ext.lwjglNatives = "natives-linux"

dependencies {
	implementation project(":projectCommon")

    implementation fileTree(dir: "$rootDir/jars/libraries/", includes: ['*.jar'])
//    implementation group: 'org.lwjgl', name: 'lwjgl', version: "${lwjglVersion}"
//    implementation group: 'org.lwjgl', name: 'lwjgl-glfw', version: "${lwjglVersion}"
//    implementation group: 'org.lwjgl', name: 'lwjgl-openal', version: "${lwjglVersion}"
//    implementation group: 'org.lwjgl', name: 'lwjgl-opengl', version: "${lwjglVersion}"
//    implementation group: 'org.lwjgl', name: 'lwjgl-stb', version: "${lwjglVersion}"
}