apply plugin: 'java'
apply plugin: 'application'

application.mainClassName = "net.minecraft.server.MinecraftServer"

dependencies {
    implementation project(":projectCommon")
    implementation group: 'com.google.guava', name: 'guava', version: '31.0.1-jre'
}

tasks.withType(JavaExec) {
    setWorkingDir(new File(workingDir.getParentFile(), "jars"))
}